#!/bin/bash

if ! which puppet 2>/dev/null 1>&2; then
  echo "$0 requires that you have Puppet installed"
  exit 1
fi

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <author>-<modulename>"
  exit 1
fi

cleanup () {
  rm -fr $LIST ${LIST}.bak $MODULEPATH
}
trap cleanup EXIT

MODULEPATH="$(mktemp -d XXXXX)"
if ! [[ -d $MODULEPATH ]]; then
  echo "Error: Unable to make a temp directory to store the module"
  exit 1
fi

LIST="$(mktemp XXXXX)"
if ! [[ -f $LIST ]]; then
  echo "Error: Unable to make a temp file for the module list"
  exit 1
fi

for module in "$@"
do
  echo "Downloading $module and its dependencies..."
  puppet module install $module --modulepath=$MODULEPATH > /dev/null
  ret_val=$?
  if [[ $ret_val -ne 0 ]]; then
    echo "Failed to download $module"
    exit 1
  fi
done

echo "Module download complete. Generating Puppetfile."

puppet module list --modulepath=$MODULEPATH > $LIST

sed -i.bak "s/^\/.*/forge 'http:\/\/forge.puppetlabs.com'\n/" $LIST
sed -i.bak "s/-/\//" $LIST
sed -i.bak "s/├── /mod '/" $LIST
sed -i.bak "s/└── /mod '/" $LIST
sed -i.bak "s/ (/', '/" $LIST
sed -i.bak "s/v\([[:digit:]]\)/1/" $LIST
sed -i.bak "s/)/'/" $LIST

echo
echo "Here is your suggested Puppetfile:"
echo "----------------------------------"
echo ""
cat $LIST

